version: '3.8'

networks:
  laraveltest:
    name: laraveltest

services:
  nginx:
    image: crmsolucoes/nginx-stable-alpine:latest
    container_name: laraveltest_nginx
    hostname: laraveltest_nginx
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laraveltest

  php:
    image: crmsolucoes/php-fpm-8.3:latest
    container_name: laraveltest_php
    hostname: laraveltest_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - laraveltest